### ISSUE TITLE
How import RichText

### ISSUE THREAD

**Issue by birnayt** [vtex-apps/rich-text#82]
**What are you trying to accomplish? Please describe.**
Hi, how can I import the RichText component?

I tried this:
`import RichText from "vtex.rich-text"`

But i received this error:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/43897881/165791003-f6f970d9-8c85-4be6-b0de-5dc5512a49a7.png">

I saw the rich-text code and found that this component is being used with an index.tsx and just one export default, so I don't know how to export without causing the preventFullImport error.

Thanks!

**Comment by birnayt** [comment]
Oh, I already found the answer =)

<img width="340" alt="Captura de Tela 2022-04-28 às 12 44 33" src="https://user-images.githubusercontent.com/43897881/165791980-0a5fa784-f983-4ef0-9946-98b5577a9646.png">

**Comment by fabionumai** [comment]
``import { index as RichText } from "vtex.rich-text"

export default function olaMundo() {
  return (
    <div>
      <RichText text="Olá mundo" />
    </div>
  )
}

**Comment by eltonleao** [comment]
> Para mim funcionou como abaixo:
> 
> ```
> import { index as RichText } from "vtex.rich-text"
> 
> export default function olaMundo() {
>   return (
>     <div>
>       <RichText text="Olá mundo" />
>     </div>
>   )
> }
> ```

aqui tbm finalmente

vlw @fabionumai !

**Comment by gabrielmagevski** [comment]
@eltonleao Valeu irmão, estava passando pelo problema 
`JSX element type 'RichText' does not have any construct or call signatures.ts(2604)`

o import { index as RichText } resolveu tudo, haha. GRATO!!!
